version: "3"
services:
  reverse-proxy:
    container_name: reverse-proxy
    build: nginx
    ports:
      - "8081:80"
    links:
      - app

  app:
    container_name: demo-app
    image: demo-app-baruch
    links:
      - db
    environment:
      - MONGO_URI=mongodb
      - MONGO_USERNAME=root
      - MONGO_PASS=pass

  db:
    container_name: mongodb
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=employees
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
     - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro


networks:
  default:
    external:
      name: jenkins
